# Site settings
title: Yale Computer Society
description: > # this means to ignore newlines until "baseurl:"
  The YCS is a student organization that promotes talks, workshops and study
  breaks related to Computer Science to Yale students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yalecompsociety.org" # the base hostname & protocol for your site

collections:
  - playbook_pages

# Build settings
# markdown: kramdown
