# Site settings
title: Yale Computer Society
description: > # this means to ignore newlines until "baseurl:"
  The YCS is a student organization that promotes talks, workshops and study
  breaks related to computer science and engineering on Yale campus.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yalecompsociety.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
